# Generated by Django 5.2.7 on 2025-10-20 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('cadence', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')])),
                ('day_of_week_deadline', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('time_deadline', models.TimeField(blank=True, help_text='Time of day <<CURRENTLY WITH RESPECT TO EST>> the report should be updated by.', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserReportAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('owner', 'Owner')], default='edit', max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='core.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='reports', through='core.UserReportAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userreportaccess',
            index=models.Index(fields=['user', 'report'], name='core_userre_user_id_478f42_idx'),
        ),
        migrations.AddIndex(
            model_name='userreportaccess',
            index=models.Index(fields=['report', 'user'], name='core_userre_report__e8fd55_idx'),
        ),
        migrations.AddConstraint(
            model_name='userreportaccess',
            constraint=models.UniqueConstraint(fields=('user', 'report'), name='uniq_user_report_access'),
        ),
    ]
