# Generated by Django 5.2.7 on 2025-10-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='day_of_week_deadline',
            field=models.IntegerField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(choices=[('CORPORATE', 'CORPORATE'), ('ACBO', 'ACBO'), ('WCBO', 'WCBO')], default='CORPORATE', help_text='Please select your work location'),
        ),
    ]
