# Generated by Django 5.2.7 on 2025-10-21 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_report_day_of_week_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(choices=[('00:00:00', '00:00'), ('00:30:00', '00:30'), ('01:00:00', '01:00'), ('01:30:00', '01:30'), ('02:00:00', '02:00'), ('02:30:00', '02:30'), ('03:00:00', '03:00'), ('03:30:00', '03:30'), ('04:00:00', '04:00'), ('04:30:00', '04:30'), ('05:00:00', '05:00'), ('05:30:00', '05:30'), ('06:00:00', '06:00'), ('06:30:00', '06:30'), ('07:00:00', '07:00'), ('07:30:00', '07:30'), ('08:00:00', '08:00'), ('08:30:00', '08:30'), ('09:00:00', '09:00'), ('09:30:00', '09:30'), ('10:00:00', '10:00'), ('10:30:00', '10:30'), ('11:00:00', '11:00'), ('11:30:00', '11:30'), ('12:00:00', '12:00'), ('12:30:00', '12:30'), ('13:00:00', '13:00'), ('13:30:00', '13:30'), ('14:00:00', '14:00'), ('14:30:00', '14:30'), ('15:00:00', '15:00'), ('15:30:00', '15:30'), ('16:00:00', '16:00'), ('16:30:00', '16:30'), ('17:00:00', '17:00'), ('17:30:00', '17:30'), ('18:00:00', '18:00'), ('18:30:00', '18:30'), ('19:00:00', '19:00'), ('19:30:00', '19:30'), ('20:00:00', '20:00'), ('20:30:00', '20:30'), ('21:00:00', '21:00'), ('21:30:00', '21:30'), ('22:00:00', '22:00'), ('22:30:00', '22:30'), ('23:00:00', '23:00'), ('23:30:00', '23:30')], unique=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='userreportaccess',
            name='uniq_user_report_access',
        ),
        migrations.AlterField(
            model_name='report',
            name='cadence',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='day_of_week_deadline',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='accessible_reports', through='core.UserReportAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userreportaccess',
            constraint=models.UniqueConstraint(fields=('user', 'report'), name='uniqe_user_report_access'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time_deadline',
            field=models.ForeignKey(blank=True, help_text='Time of day (WITH RESPECT TO YOUR TIME ZONE) the report should be updated by.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.timeslot'),
        ),
    ]
